import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1], a[2])
a[0] = 5
print(a)
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)                
print(b[0, 0], b[0, 1], b[1, 0]) 
a = np.zeros((2,2))
print(a)
b = np.ones((1,2))
print(b)
c = np.full((2,2), 7)
print(c)
d = np.eye(2)
print("d:")
print(d)
e = np.random.random((2,2))
print("e:")
print(e)
print("d*e:")
print(d*e)
f=np.concatenate((d, e), axis=0)
print(f)
g=np.concatenate((d, e), axis=1)
print(g)
data = np.array([1.0, 2.0])
data = data * 1.6
print(data)

